name: Lean 4 CI

on:
  push:
    branches:
      - "*"
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  LEAN_ABORT_ON_FAILED_IMPORTS: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
      - run: lake update
      - run: lake build Book
      - run: lake build UniGeo
      - run: lake build LeanGeo

      - name: Build documentation
        run: lake -R -Kenv=dev build LeanGeo:docs
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      - name: Make sure the cache works
        run: |
          mv docs/docs .lake/build/doc